const matrix = sarduMatrix.create(8, 8, DigitalPin.P1, 64)
matrix.clearBuffer()
matrix.setPixel(0, 0, neopixel.colors(NeoPixelColors.White))
matrix.show()
matrix.setBrightness(128)
matrix.clearColumns(0, 1)
matrix.clearRows(0, 1)
matrix.clearArea(0, 0, 1, 1)
matrix.clear()
matrix.interruptAndClear()
